name: Docker Website Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Create config files from secrets
      run: |
        # Create config files in the correct location
        echo '${{ secrets.CHIRPSTACK_CONFIG }}' > MeterThing/meterthing/backend/chirpstack_config.json
        echo '${{ secrets.CREDENTIALS_JSON }}' > MeterThing/meterthing/backend/credentials.json
      
    - name: Build and start containers
      working-directory: MeterThing
      run: |
        # Run docker compose from the proper directory
        docker compose -f docker-compose.yml up -d
        
    - name: Wait for services to start
      run: |
        echo "Waiting for services to start up..."
        sleep 30
        
    - name: Check if backend is running
      run: |
        if curl -s http://localhost:8000 > /dev/null; then
          echo "Backend is up and running!"
        else
          echo "Backend failed to start"
          exit 1
        fi
        
    - name: Check if frontend is running
      run: |
        if curl -s http://localhost:5173 > /dev/null; then
          echo "Frontend is up and running!"
        else
          echo "Frontend failed to start"
          exit 1
        fi
    
    - name: Run integration tests
      run: |
        # Add your test commands here
        echo "Running integration tests..."
        
    - name: Collect logs if failure
      if: failure()
      working-directory: MeterThing
      run: |
        echo "Collecting container logs for debugging..."
        docker compose logs
        
    - name: Stop containers
      if: always()
      working-directory: MeterThing
      run: |
        docker compose down